# Generated by Django 4.1.13 on 2026-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_runtime_prompt_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragdatabase",
            name="embedding_api_base",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="建库Embedding地址"
            ),
        ),
        migrations.AddField(
            model_name="ragdatabase",
            name="embedding_dimension",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="向量维度"
            ),
        ),
        migrations.AddField(
            model_name="ragdatabase",
            name="embedding_model",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="建库Embedding模型"
            ),
        ),
        migrations.AddField(
            model_name="ragdatabase",
            name="index_status",
            field=models.CharField(
                default="needs_rebuild", max_length=20, verbose_name="索引状态"
            ),
        ),
        migrations.AddField(
            model_name="ragruntimeconfig",
            name="embedding_api_base",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Embedding API地址"
            ),
        ),
        migrations.AddField(
            model_name="ragruntimeconfig",
            name="embedding_api_key",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Embedding API Key"
            ),
        ),
        migrations.AddField(
            model_name="ragruntimeconfig",
            name="embedding_model",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Embedding模型"
            ),
        ),
        migrations.AddField(
            model_name="ragruntimeconfig",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=1024, verbose_name="最大输出Token数"
            ),
        ),
        migrations.AlterField(
            model_name="ragdatabase",
            name="mineru_output_directory",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="历史MinerU输出目录",
            ),
        ),
        migrations.AlterField(
            model_name="ragruntimeconfig",
            name="dashscope_api_key",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="历史DashScope API Key"
            ),
        ),
        migrations.AlterField(
            model_name="ragruntimeconfig",
            name="deepseek_max_tokens",
            field=models.PositiveIntegerField(
                default=1024, verbose_name="历史最大输出Token数"
            ),
        ),
        migrations.AlterField(
            model_name="ragruntimeconfig",
            name="rag_prompt_template",
            field=models.TextField(
                default="你是校园资料问答助手。请严格依据提供的资料回答问题，不要使用资料之外的知识。\n\n        ## 核心要求\n        **字数限制**：回答必须严格控制在150字以内，优先提供最关键的信息。\n\n        ## 回答规则\n        1. **检索文档有相关内容时**：\n        - 优先依据文档中的准确信息回答\n        - 若用户问题中的名称与文档不一致，以文档为准并自然纠正\n        - 保留文档中的HTTP/HTTPS链接\n\n        2. **检索文档为空或无关时**：\n        - 资料为空、无关或不足时，明确说明“根据现有资料无法确定”，不要猜测\n\n        ## 表达规范\n        - 直接作答，不提及检索或文档来源\n        - 语言自然简洁，优先给出直接结论\n        - 中文问答用中文，英文用英文\n        - 内容超限时优先保留：核心科普事实 > 关键数据 > 链接\n\n        ## 问题相关性优先：\n        - 仅回答与用户问题直接相关的内容\n        - 禁止扩展无关科普\n        - 若问题为简单计算/常识题，仅给出答案，可附简短引导后续提问\n\n        ---\n        用户问题: {question}\n\n        检索文档:\n        {context}\n\n        请在150字内回答:",
                verbose_name="回答提示词模板",
            ),
        ),
    ]
