# Generated by Django 4.1.13 on 2026-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_ragdatabase_embedding_api_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragruntimeconfig",
            name="llm_model",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="大语言模型"
            ),
        ),
    ]
